spring.application.name=crudPrac

spring.datasource.url=jdbc:mysql://localhost:3306/restapi
spring.datasource.username=prac_user
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ??? ?? ????
spring.thymeleaf.cache=false
# ?? ??? ???
spring.web.resources.cache.period=0
# DevTools ???
spring.devtools.restart.enabled=true